/**
 * SchoolVote API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateSessionResponse } from './createSessionResponse';

export interface GetAllSessionsResponse {
  sessions?: Array<CreateSessionResponse> | null;
}
