/**
 * SchoolVote API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface RegisterVoterResponse {
  id?: string;
  authKey?: string | null;
  name?: string | null;
  maxFemaleVotes?: number;
  maxMaleVotes?: number;
  grade?: number;
}
