/**
 * SchoolVote API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface RegisterAdministratorCommand {
  username?: string | null;
  password?: string | null;
}
