/**
 * SchoolVote API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface VoterLoginResponse {
  jwt?: string | null;
  authorizedGrade?: number;
  maleVotes?: number;
  femaleVotes?: number;
}
