// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SchoolVote.API.Infrastructure.Persistence;

#nullable disable

namespace SchoolVote.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SchoolVote.API.Common.Entities.Administrators", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Administrators");
                });

            modelBuilder.Entity("SchoolVote.API.Common.Entities.Nominations", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<int>("GradeAllocated")
                        .HasColumnType("integer");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfilePictureUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("VotingSessionsId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VotingSessionsId");

                    b.ToTable("Nominations");
                });

            modelBuilder.Entity("SchoolVote.API.Common.Entities.Voters", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AuthName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("AuthorizedGrade")
                        .HasColumnType("integer");

                    b.Property<bool>("Voted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("VotingSessionsId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VotingSessionsId");

                    b.ToTable("Voters");
                });

            modelBuilder.Entity("SchoolVote.API.Common.Entities.VotersCasted", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateVoted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("NominatedId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VoterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VotingSessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NominatedId");

                    b.HasIndex("VoterId");

                    b.HasIndex("VotingSessionId");

                    b.ToTable("VotesCasted");
                });

            modelBuilder.Entity("SchoolVote.API.Common.Entities.VotingSessions", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdministratorId")
                        .HasColumnType("uuid");

                    b.Property<string>("VotingSessionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AdministratorId");

                    b.ToTable("VotingSessions");
                });

            modelBuilder.Entity("SchoolVote.API.Common.Entities.Nominations", b =>
                {
                    b.HasOne("SchoolVote.API.Common.Entities.VotingSessions", null)
                        .WithMany("Nominations")
                        .HasForeignKey("VotingSessionsId");
                });

            modelBuilder.Entity("SchoolVote.API.Common.Entities.Voters", b =>
                {
                    b.HasOne("SchoolVote.API.Common.Entities.VotingSessions", null)
                        .WithMany("Voters")
                        .HasForeignKey("VotingSessionsId");
                });

            modelBuilder.Entity("SchoolVote.API.Common.Entities.VotersCasted", b =>
                {
                    b.HasOne("SchoolVote.API.Common.Entities.Nominations", "Nominated")
                        .WithMany("VotersCasted")
                        .HasForeignKey("NominatedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolVote.API.Common.Entities.Voters", "Voter")
                        .WithMany("VotersCasted")
                        .HasForeignKey("VoterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolVote.API.Common.Entities.VotingSessions", "VotingSession")
                        .WithMany("VotersCasted")
                        .HasForeignKey("VotingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nominated");

                    b.Navigation("Voter");

                    b.Navigation("VotingSession");
                });

            modelBuilder.Entity("SchoolVote.API.Common.Entities.VotingSessions", b =>
                {
                    b.HasOne("SchoolVote.API.Common.Entities.Administrators", "Administrator")
                        .WithMany("votingSessions")
                        .HasForeignKey("AdministratorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Administrator");
                });

            modelBuilder.Entity("SchoolVote.API.Common.Entities.Administrators", b =>
                {
                    b.Navigation("votingSessions");
                });

            modelBuilder.Entity("SchoolVote.API.Common.Entities.Nominations", b =>
                {
                    b.Navigation("VotersCasted");
                });

            modelBuilder.Entity("SchoolVote.API.Common.Entities.Voters", b =>
                {
                    b.Navigation("VotersCasted");
                });

            modelBuilder.Entity("SchoolVote.API.Common.Entities.VotingSessions", b =>
                {
                    b.Navigation("Nominations");

                    b.Navigation("Voters");

                    b.Navigation("VotersCasted");
                });
#pragma warning restore 612, 618
        }
    }
}
